use crate::models::{CookieCleanupGuide, SecurityChecklistItem};

pub(crate) fn cookie_cleanup_guides() -> Vec<CookieCleanupGuide> {
    vec![
        CookieCleanupGuide {
            browser: "Chrome / Chromium / Brave",
            steps: vec![
                "Open Settings > Privacy and security > Delete browsing data.",
                "Set Time range to All time.",
                "Select Cookies and other site data.",
                "Delete data, then restart the browser.",
            ],
        },
        CookieCleanupGuide {
            browser: "Microsoft Edge",
            steps: vec![
                "Open Settings > Privacy, search, and services.",
                "Under Clear browsing data, choose what to clear.",
                "Set Time range to All time.",
                "Select Cookies and other site data, clear it, then restart Edge.",
            ],
        },
        CookieCleanupGuide {
            browser: "Firefox",
            steps: vec![
                "Open Settings > Privacy & Security.",
                "Under Cookies and Site Data, click Clear Data.",
                "Select Cookies and Site Data.",
                "Clear it, then restart Firefox.",
            ],
        },
    ]
}

pub(crate) fn security_checklist() -> Vec<SecurityChecklistItem> {
    vec![
        SecurityChecklistItem {
            category: "Password",
            task: "Change passwords for email, password manager, banking, work, social, gaming, and developer accounts.",
            why: "A stolen browser session often exposes saved passwords or account reset paths.",
            done: false,
        },
        SecurityChecklistItem {
            category: "Password",
            task: "Use unique passwords generated by a password manager.",
            why: "Reuse lets one stolen password unlock other accounts.",
            done: false,
        },
        SecurityChecklistItem {
            category: "2FA",
            task: "Verify 2FA is enabled on every important account.",
            why: "Info stealers can bypass some active sessions, but 2FA still protects fresh sign-ins.",
            done: false,
        },
        SecurityChecklistItem {
            category: "2FA",
            task: "Rotate recovery codes and remove unknown authenticators or phone numbers.",
            why: "Attackers may add fallback methods after gaining access.",
            done: false,
        },
        SecurityChecklistItem {
            category: "Passkey",
            task: "Add passkeys where supported, starting with email and password manager accounts.",
            why: "Passkeys reduce phishing and password replay risk.",
            done: false,
        },
        SecurityChecklistItem {
            category: "Access tokens",
            task: "Revoke unknown OAuth apps, browser extensions, API tokens, PATs, SSH keys, and app passwords.",
            why: "Tokens can stay valid even after a password change.",
            done: false,
        },
        SecurityChecklistItem {
            category: "Sessions",
            task: "Use each service security page to sign out other devices and review recent activity.",
            why: "This invalidates stolen sessions that are still accepted by the service.",
            done: false,
        },
    ]
}
